name: actionlint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # ratchet:actions/checkout@v4

      - name: Download actionlint
        shell: bash
        run: |
          bash <(curl -s https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Run actionlint
        shell: bash
        run: ./actionlint -color
